# Pharmagen - Pharmacogenetic Prediction and Therapeutic Efficacy
# Copyright (C) 2025 Adrim Hamed Outmani
# Licensed under the GNU GPLv3. See LICENSE file in the project root.
#
# src/config/models.toml

# ==========================================
# MODELO 1: Phenotype_Effect_Outcome
# ==========================================
[TwoTowerGAT]
# Features && Targets Definition

cols = ["drugs_cid", "drugs", "genotype", "gene", "phenotype_category"]
features = ["drugs_cid", "genotype"]
targets = ["phenotype_category"]
#stratify_col = "phenotype_category"  # Column used for stratified splitting


# --- Graph Input Dimensions (HARD REQUIREMENTS) ---
drug_in_features = 25   
drug_edge_dim = 7
# Haplo Tower (From all_in_one.py)
haplo_in_features = 9   # [backbone, split/merge, ref, alt, score]
haplo_edge_dim = 3      # [backbone_link, ref_path, alt_path] (If you applied the fix I suggested)
haplo_idx = 2    # Use 0 if you did NOT apply the edge fix in all_in_one.py

# --- OPTUNA SEARCH SPACE ---
# These define the range/choices for the Tuner
[TwoTowerGAT.optuna]
### --- Arquitectura (GNN & Towers) --- ###
patience = 10
epochs = 100
# "categorical" 
embedding_dim = ["categorical", 256, 512]
hidden_dim = ["categorical", 512, 768, 1024]

# "int" 
n_layers = ["int", 4, 6]

# Attention Heads (GATv2).
heads = ["categorical", 8, 12, 16]

# "float" 
dropout_rate = ["float", 0.35, 0.6]

### --- Optimización (Training Loop) --- ###

# "log"
learning_rate = ["log", 2e-4, 8e-4]
weight_decay = ["log", 1e-5, 1e-4]

# Batch size afecta la generalización y el uso de VRAM.
batch_size = ["categorical", 64, 128]

# --- Función de Pérdida (Loss Hyperparams) ---
# Si usas FocalLoss o AsymmetricLoss (definidas en losses.py), estos parámetros son críticos.
# gamma: Controla qué tanto se penalizan los ejemplos difíciles.
gamma = ["float", 2.0, 3.5] 
# asl_clip: Para AsymmetricLoss, controla el recorte de negativos fáciles.
asl_clip = ["float", 0.1, 0.25]

[TwoTowerGAT.params]
# Architecture
embedding_dim = 256
hidden_dim = 512
n_layers = 5
heads = 8
dropout_rate = 0.4859822310846825
# Optimization
learning_rate = 0.00040560545904101556
weight_decay = 4.089545393645109e-05
batch_size = 64
gamma = 2.912048826308894
asl_clip = 0.1575118661574606


# ==========================================