# Pharmagen - Pharmacogenetic Prediction and Therapeutic Efficacy
# Copyright (C) 2025 Adrim Hamed Outmani
# Licensed under the GNU GPLv3. See LICENSE file in the project root.
#
# src/config/models.toml

# ==========================================
# MODELO 1: Phenotype_Effect_Outcome
# ==========================================
[TwoTowerGAT]
# Features && Targets Definition

cols = ["drugs_cid", "drugs", "genotype", "gene", "phenotype_category"]
features = ["drugs_cid", "genotype"]
targets = ["phenotype_category"]
stratify_col = "phenotype_category"  # Column used for stratified splitting


# --- Graph Input Dimensions (HARD REQUIREMENTS) ---
drug_in_features = 25   
drug_edge_dim = 7
# Haplo Tower (From all_in_one.py)
haplo_in_features = 9   # [backbone, split/merge, ref, alt, score]
haplo_edge_dim = 3      # [backbone_link, ref_path, alt_path] (If you applied the fix I suggested)
haplo_idx = 2    # Use 0 if you did NOT apply the edge fix in all_in_one.py

# --- OPTUNA SEARCH SPACE ---
# These define the range/choices for the Tuner
[TwoTowerGAT.optuna]
### --- Arquitectura (GNN & Towers) --- ###
patience = 15
epochs = 50
# "categorical" 
embedding_dim = ["categorical", 64, 128, 256, 512]
hidden_dim = ["categorical", 128, 256, 512]

# "int" 
n_layers = ["int", 2, 5]

# Attention Heads (GATv2).
heads = ["categorical", 2, 4, 8]

# "float" 
dropout_rate = ["float", 0.1, 0.5]

### --- Optimización (Training Loop) --- ###

# "log"
learning_rate = ["log", 1e-5, 5e-2]
weight_decay = ["log", 1e-6, 1e-3]

# Batch size afecta la generalización y el uso de VRAM.
batch_size = ["categorical", 64, 128, 256]

# --- Función de Pérdida (Loss Hyperparams) ---
# Si usas FocalLoss o AsymmetricLoss (definidas en losses.py), estos parámetros son críticos.
# gamma: Controla qué tanto se penalizan los ejemplos difíciles.
gamma = ["float", 0.5, 4.0] 
# asl_clip: Para AsymmetricLoss, controla el recorte de negativos fáciles.
asl_clip = ["float", 0.0, 0.2]

[TwoTowerGAT.params]
# Architecture
embedding_dim = 128
hidden_dim = 64
n_layers = 3
heads = 4
dropout_rate = 0.1

# Optimization
learning_rate = 0.001
weight_decay = 1e-5
batch_size = 32